name: Deploy bot

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Build bot
        run: |
          source "$HOME/.cargo/env"
          cargo build --release

      - name: Copy bot executable
        run: |
          cp target/release/discord_bot /home/github-runner/discord_bot/discord_bot
          chmod +x /home/github-runner/discord_bot/discord_bot

      - name: Restart bot
        run: sudo systemctl restart discord-bot