name: Deploy bot

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Build bot
        run: |
          source "$HOME/.cargo/env"
          cargo build --release